Importing Dependencies

In [38]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss

Loading the Dataset

In [39]:
df=pd.read_csv("heart_disease_data.csv")
df.head(10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   
6   56    0   1       140   294    0        0      153      0      1.3      1   
7   44    1   1       120   263    0        1      173      0      0.0      2   
8   52    1   2       172   199    1        1      162      0      0.5      2   
9   57    1   2       150   168    0        1      174      0      1.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1  
6   0     2       1  
7   0     3       1  
8   0     3       1  
9   0     2       1

In [40]:
df.shape

(303, 14)

Checking for missing values in the Dataset

In [41]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

Statistical information about the data

In [42]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

Checking the target column

In [43]:
pd.DataFrame(df["target"].value_counts())

#1---> Defective Heart
#0---> Healthy Heart

target
1     165
0     138

Splitting the features and target from the dataset

In [44]:
X=df.drop(columns='target',axis=1)
y=df['target']

In [45]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [46]:
pd.DataFrame(y.head())

target
0       1
1       1
2       1
3       1
4       1

Splitting the dataset into Training data and Test data

In [47]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,stratify=y,random_state=10)

In [48]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(257, 13) (46, 13) (257,) (46,)


Logistic Regression Model

In [49]:
from sklearn.linear_model import LogisticRegression

In [50]:
model=LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [51]:
# Get predicted probabilities for each class on the test set
y_pred_prob = model.predict_proba(X_test)
y_pred_prob

array([[0.24428396, 0.75571604],
       [0.7131185 , 0.2868815 ],
       [0.07541762, 0.92458238],
       [0.83353165, 0.16646835],
       [0.98985542, 0.01014458],
       [0.0535777 , 0.9464223 ],
       [0.99517294, 0.00482706],
       [0.49410697, 0.50589303],
       [0.21956314, 0.78043686],
       [0.02736314, 0.97263686],
       [0.0096509 , 0.9903491 ],
       [0.30006513, 0.69993487],
       [0.96770033, 0.03229967],
       [0.91918576, 0.08081424],
       [0.06335916, 0.93664084],
       [0.83512879, 0.16487121],
       [0.3298579 , 0.6701421 ],
       [0.43554488, 0.56445512],
       [0.0958179 , 0.9041821 ],
       [0.96180497, 0.03819503],
       [0.9272972 , 0.0727028 ],
       [0.44316673, 0.55683327],
       [0.92396596, 0.07603404],
       [0.98121151, 0.01878849],
       [0.68592542, 0.31407458],
       [0.05706443, 0.94293557],
       [0.84866034, 0.15133966],
       [0.73164591, 0.26835409],
       [0.0945851 , 0.9054149 ],
       [0.40273068, 0.59726932],
       [0.

In [52]:
# Calculate log loss
logloss = log_loss(y_test, y_pred_prob)
print("Log Loss: ",logloss)

Log Loss:  0.3442126949170099


Random Forest Classifier Model

In [53]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [55]:
# Get predicted probabilities for each class on the test set
y_pred_prob = classifier.predict_proba(X_test)
print("Predicted Probabilities:\n",y_pred_prob)

Predicted Probabilities:
 [[0.19 0.81]
 [0.64 0.36]
 [0.06 0.94]
 [0.49 0.51]
 [0.99 0.01]
 [0.2  0.8 ]
 [0.85 0.15]
 [0.11 0.89]
 [0.35 0.65]
 [0.15 0.85]
 [0.   1.  ]
 [0.26 0.74]
 [0.95 0.05]
 [0.79 0.21]
 [0.11 0.89]
 [0.61 0.39]
 [0.31 0.69]
 [0.47 0.53]
 [0.13 0.87]
 [0.83 0.17]
 [0.65 0.35]
 [0.56 0.44]
 [0.87 0.13]
 [1.   0.  ]
 [0.79 0.21]
 [0.07 0.93]
 [0.84 0.16]
 [0.57 0.43]
 [0.08 0.92]
 [0.11 0.89]
 [0.93 0.07]
 [0.71 0.29]
 [0.23 0.77]
 [0.78 0.22]
 [0.18 0.82]
 [0.42 0.58]
 [0.2  0.8 ]
 [0.26 0.74]
 [0.06 0.94]
 [0.17 0.83]
 [0.22 0.78]
 [0.65 0.35]
 [0.72 0.28]
 [0.92 0.08]
 [0.23 0.77]
 [0.14 0.86]]


In [56]:
# Calculate log loss
logloss = log_loss(y_test, y_pred_prob)
print("Log Loss: ",logloss)

Log Loss:  0.33914654710915665


Support Vector Classifier Model

In [57]:
from sklearn.svm import SVC
from sklearn.calibration import CalibratedClassifierCV

In [58]:
svm_classifier = SVC(probability=True)
svm_classifier.fit(X_train, y_train)

SVC(probability=True)

In [59]:
# Get decision values for each class on the test set
decision_values = svm_classifier.decision_function(X_test)
# Use CalibratedClassifierCV to convert decision values to probabilities
calibrated_svm = CalibratedClassifierCV(estimator=svm_classifier, method='sigmoid')
calibrated_svm.fit(X_train, y_train)

CalibratedClassifierCV(estimator=SVC(probability=True))

In [60]:
# Get predicted probabilities for each class on the test set
y_pred_prob = calibrated_svm.predict_proba(X_test)
print("Predicted Probabilities:\n",y_pred_prob)

Predicted Probabilities:
 [[0.53210808 0.46789192]
 [0.22471607 0.77528393]
 [0.08494315 0.91505685]
 [0.40172412 0.59827588]
 [0.59605593 0.40394407]
 [0.81069717 0.18930283]
 [0.86862139 0.13137861]
 [0.42713804 0.57286196]
 [0.28994563 0.71005437]
 [0.18922764 0.81077236]
 [0.2032415  0.7967585 ]
 [0.23191135 0.76808865]
 [0.83267223 0.16732777]
 [0.66592371 0.33407629]
 [0.36383706 0.63616294]
 [0.74830788 0.25169212]
 [0.19756207 0.80243793]
 [0.54645298 0.45354702]
 [0.21038827 0.78961173]
 [0.79966833 0.20033167]
 [0.79821104 0.20178896]
 [0.50465671 0.49534329]
 [0.45397334 0.54602666]
 [0.55178243 0.44821757]
 [0.33671399 0.66328601]
 [0.40352492 0.59647508]
 [0.30133969 0.69866031]
 [0.55599354 0.44400646]
 [0.2046102  0.7953898 ]
 [0.17840124 0.82159876]
 [0.56272696 0.43727304]
 [0.67867525 0.32132475]
 [0.35594175 0.64405825]
 [0.69233255 0.30766745]
 [0.11160983 0.88839017]
 [0.25969324 0.74030676]
 [0.5899689  0.4100311 ]
 [0.40386347 0.59613653]
 [0.58912977 0.41087023]

In [61]:
# calculate log loss
logloss = log_loss(y_test, y_pred_prob)
print(f"Log Loss: ",logloss)

Log Loss:  0.6085842488545063


XGBoost Model

In [62]:
import xgboost as xgb

In [63]:
xgb_classifier = xgb.XGBClassifier(objective="multi:softprob", num_class=len(set(y)))
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=2,
              num_parallel_tree=None, ...)

In [64]:
# Get predicted probabilities for each class on the test set
y_pred_prob = xgb_classifier.predict_proba(X_test)
print("Predicted Probabilities:\n",y_pred_prob)

Predicted Probabilities:
 [[1.71069596e-02 9.82893050e-01]
 [7.69993603e-01 2.30006397e-01]
 [1.33255118e-04 9.99866724e-01]
 [9.82336581e-01 1.76634416e-02]
 [9.99866962e-01 1.32983070e-04]
 [3.79288271e-02 9.62071121e-01]
 [9.92579520e-01 7.42046256e-03]
 [1.88795067e-02 9.81120527e-01]
 [3.68514284e-02 9.63148594e-01]
 [8.72233231e-03 9.91277695e-01]
 [1.36887349e-04 9.99863148e-01]
 [5.86117990e-02 9.41388249e-01]
 [9.99761283e-01 2.38705063e-04]
 [9.99148488e-01 8.51495774e-04]
 [3.87593615e-03 9.96124089e-01]
 [8.77619803e-01 1.22380190e-01]
 [4.30615200e-03 9.95693803e-01]
 [8.88842762e-01 1.11157276e-01]
 [6.07267097e-02 9.39273238e-01]
 [9.89435554e-01 1.05643757e-02]
 [5.56478381e-01 4.43521559e-01]
 [6.00698531e-01 3.99301529e-01]
 [9.78763521e-01 2.12364551e-02]
 [9.99895930e-01 1.04058621e-04]
 [9.06538129e-01 9.34618711e-02]
 [1.43417937e-03 9.98565853e-01]
 [9.98519838e-01 1.48014864e-03]
 [9.17024553e-01 8.29754248e-02]
 [9.79159842e-04 9.99020815e-01]
 [2.12528165e-02 

In [65]:
logloss = log_loss(y_test, y_pred_prob)
print("Log Loss: ",logloss)

Log Loss:  0.5281537802482652


Accuracy Score on Random Forest Classifier Model

In [66]:
X_train_prediction=classifier.predict(X_train)
X_train_accuracy=accuracy_score(X_train_prediction,y_train)
print("Training Accuracy: ",X_train_accuracy*100,"%")

Training Accuracy:  100.0 %


In [67]:
X_test_prediction=classifier.predict(X_test)
X_test_accuracy=accuracy_score(X_test_prediction,y_test)
print("Test Accuracy: ",X_test_accuracy*100,"%")

Test Accuracy:  89.13043478260869 %


Building Prediction System

In [68]:
input_data=(67,1,0,120,229,0,0,129,1,2.6,1,2,3)
data=np.asarray(input_data)
data_reshaped=data.reshape(1,-1)
prediction=classifier.predict(data_reshaped)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [69]:
if prediction[0]==1:
    print("Patient is suspected to be suffering from heart disease")
else:
    print("Patient has healthy heart")

Patient has healthy heart
